version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: devsu_test
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - devsu-network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - devsu-network

  client-service:
    build:
      context: ./client-service
      dockerfile: Dockerfile
    container_name: client-service
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/devsu_test
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=1234
      - CLIENT_SERVICE_URL=http://client-service:8080
      - RABBITMQ_HOST=rabbitmq
    depends_on:
      - mysql
      - rabbitmq
    networks:
      - devsu-network

  finance-service:
    build:
      context: ./finance-service
      dockerfile: Dockerfile
    container_name: finance-service
    ports:
      - "8090:8090"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/devsu_test
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=1234
      - CLIENT_SERVICE_URL=http://client-service:8080
      - RABBITMQ_HOST=rabbitmq
    depends_on:
      - mysql
      - rabbitmq
      - client-service
    networks:
      - devsu-network

networks:
  devsu-network:

volumes:
  mysql-data:
