version: "3.8"

services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: devsu_test
    ports:
      - "3306:3306"
    networks:
      - devsu-network

  rabbitmq:
    image: rabbitmq:3-management
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - devsu-network

  client-service:
    image: client-service:latest
    build:
      context: ./client-service
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - devsu-network
    depends_on:
      - mysql
      - rabbitmq

  finance-service:
    image: finance-service:latest
    build:
      context: ./finance-service
      dockerfile: Dockerfile
    ports:
      - "8090:8090"
    networks:
      - devsu-network
    depends_on:
      - mysql
      - rabbitmq

networks:
  devsu-network:
    driver: bridge
